### ISSUE TITLE
cannot connect swoogle and watson search engin

### ISSUE THREAD

**Issue by asevergreen** [gorkemgiray/textcoherence#1]
Hello, are swoogle and watson's api services still running? I can't get them, do you have any suggestions? Hope to get your help and thanks a lot.

**Comment by gorkemgiray** [comment]
Swoogle and Watson used to be public ontology search engines. 

I was using Swoogle REST API (http://logos.cs.umbc.edu:8080/swoogle31/q?queryType=search_swd_ontology&searchString=" + String1 + "+" + String2 + "&key=demo"). It seems that this REST API does not work anymore. You can check Swoogle website (http://swoogle.umbc.edu/2006/index.php?option=com_swoogle_manual&manual=search_overview) and contact Swoogle team for more information.

I was using uk.ac.open.kmi.watson.clientapi library. You can consult Watson team for a recent working version of the library. You can reach them via http://kmi.open.ac.uk/technologies/name/watson/.

Search in ontology search engines are being done in OntolojiArama.java. If Swoogle and Watson do not work anymore, you can try to use other ontology search engines and update the code in OntolojiArama.java. Another solution could be to create a local offline ontology repository and bypass online ontology search step.

**Comment by asevergreen** [comment]
Thank you for your reply! I am trying to contact the Swoogle team, and the watson library I downloaded is from http://babel.ls.fi.upm.es/~iperez/imdea-watson/releases/. I suspect it is not the latest version, but I cannot find another download link. 
This version of Watson will get org.xml.sax.SAXParseException error at runtime. Would you mind telling me where did your Watson package come from?
Thank you very much.

**Comment by gorkemgiray** [comment]
I uploaded Watson files I used to "Source Code" directory.

**Comment by asevergreen** [comment]
Thank you so much! I'll try it!
